### ISSUE TITLE
Portgal Plugin is no Responsive

### ISSUE THREAD

**Issue by elvisito** [faustynm/nihon-portgal#1]
Good Morning.

Thanks for excelent PlugIn... Is the best Gallery Plugin for Wordpress... but there is a problem: The gallery Imagens Carousel is not responsive for mobile devices.  Images no fit in height display.....

Please Help Me.

**Comment by faustynm** [comment]
Please send me a screenshot (URL) and write what browser you're using or devices

**Comment by elvisito** [comment]
Browsers: Chrome, FireFox, Android devices.  Happen on your sample website when shrink resize browser on Windows PC..... and Android no need resizes to occur the event.

 http://gorges.pl/portgal/?page_id=154

![issue_portgal_1](https://cloud.githubusercontent.com/assets/25680293/22834847/98fc68c8-ef84-11e6-9ba2-84a30385229c.jpg)

Thanks for any solve.....

**Comment by faustynm** [comment]
I fixed my script, now it should be OK

**Comment by elvisito** [comment]
Excelente !!!... Very good... Thanks for all!!.
